---
kind: pipeline
type: docker
name: backend

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: build
    image: golang:1.20
    volumes:
      - name: deps
        path: /go
    commands:
      - go build

  - name: test
    image: golang:1.20
    volumes:
      - name: deps
        path: /go
    commands:
      - go test

  - name: linter
    image: golang:1.20
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s
      - ./bin/golangci-lint run --timeout 5m
      - rm -r ./bin/

  - name: telegram
    image: appleboy/drone-telegram
    settings:
      to: 790376882
      format: markdown
      token:
        from_secret: telegram_token
    when:
      status:
      - success
      - failure

volumes:
  - name: deps
    host:
      path: /var/lib/cache/godeps/
